restaurant_managment-main/input/urls.py
import os
from django.urls import path, include

from django.contrib.auth import views as auth_views #new
urlpatterns = [
path('', include('input.Category.urls')),
path('', include('input.Items.urls')),
]
 

restaurant_managment-main/purchases/Supplier/urls.py
import os
from django.urls import path, include
from django.contrib.auth import views as auth_views #new
from .views import Supplier_view, SupplierJson
urlpatterns = [
path('Supplier',Supplier_view.as_view(),name='supplier'),
path('SupplierJson',SupplierJson.as_view(),name='SupplierJson'),
]
 

restaurant_managment-main/purchases/urls.py
import os
from django.urls import path, include
from django.contrib.auth import views as auth_views #new
from purchases.views import PurchaseInvoicelocals,max_number
urlpatterns = [
path('', include('purchases.Supplier.urls')),
path('purchases', PurchaseInvoicelocals.as_view(),name='purchases'),
path('max_number', max_number,name='max_number'),
]
 

restaurant_managment-main/restaurant_managment/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users.views import CustomLoginView, ResetPasswordView, ChangePasswordView
from users.forms import LoginForm
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('configrate.urls')),
    path('', include('input.urls')),
    path('', include('purchases.urls')),
    path('', include('users.urls')),
    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login',template_name='users/login.html'), name='logout'),
    re_path(r'^reset-password/$', ResetPasswordView.as_view(), name='reset_password'),
    re_path(r'^change-password/$', ChangePasswordView.as_view(), name='change_password'),
    #path('password-reset-confirm/<uidb64>/<token>/',
     #    auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
      #   name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('password-change/', ChangePasswordView.as_view(), name='password_change'),

    url('oauth/', include('social_django.urls', namespace='social')),

]  


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

restaurant_managment-main/purchases/models.py
from django.db import models
from input.models import Items,Store
# Create your models here.
class Supplier(models.Model):
    name_lo = models.CharField("الاسم المحلي",max_length=50)
    name_fk = models.CharField("الاسم الاجنبي",max_length=50)
    phone   = models.CharField("رقم الجوال",max_length=50,blank=True,null=True)
    is_stop = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name_lo


class Purchases(models.Model):
    number= models.IntegerField("رقم الفاتورة",null=False)
    date= models.DateField("التاريخ",null=False)
    notes= models.TextField("الملاحظة")
    supplir = models.ForeignKey(Supplier,on_delete=models.PROTECT,verbose_name="المورد"),
    amount = models.FloatField("الإجمالي",null=True,blank=True)
    store = models.ForeignKey(Store,on_delete=models.CASCADE,verbose_name="المخز")

class PurchasesDetails(models.Model):
    purchases= models.ForeignKey(Purchases, on_delete=models.CASCADE)
    items= models.ForeignKey(Items, on_delete=models.CASCADE,verbose_name="الصنف")
    price= models.FloatField("السعر",null=True)
    qty = models.IntegerField("الكمية",null=True)
    date_end = models.DateField("تاريخ الإنتهاء")    
    
    
    

restaurant_managment-main/purchases/Supplier/forms.py
from django import forms
from purchases.models import Supplier

class SupplierForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(SupplierForm, self).__init__(*args, **kwargs)
        self.fields['name_lo'].widget.attrs.update({
            'class': 'formset-field  form-control'})
        self.fields['name_fk'].widget.attrs.update({
            'class': 'formset-field  form-control'})
        self.fields['phone'].widget.attrs.update({
            'class': 'formset-field  form-control'})
        self.fields['is_stop'].widget.attrs.update({
            'class': 'formset-field  form-control'})
      

    
    class Meta:
        model=Supplier
        fields="__all__"
        execute="created"

restaurant_managment-main/purchases/Supplier/views.py
from django.shortcuts import render
from django.urls import reverse
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.utils.html import escape
from django.views.generic.edit import CreateView
from django.http import  JsonResponse, HttpResponse
from django.contrib.auth import authenticate
from django.contrib.auth import views as auth_views #new
from django.views import View

from purchases.models import Supplier
from .forms import SupplierForm

from django.core import serializers
from django.shortcuts import get_object_or_404
from django.http import QueryDict

class Supplier_view(CreateView):

    def get(self, request, *args, **kwargs):
        if 'id' in request.GET.keys():
            if request.GET.get('id'):
                data=Supplier.objects.filter(pk=request.GET.get('id'))
                
                
  
                result={'status':1,'data':serializers.serialize('json',data)}
            else:
                result={'status':0,'data':''}
            return JsonResponse(result)
        else:
        
            Uni=Supplier.objects.all()
            fileduse=SupplierForm()
            context={
                "Items":Uni,
                "filed":fileduse
            }
    
        return render(request, 'purchases/Supplier/Supplier.html',context)

    def post(self, request, *args, **kwargs):
        form = SupplierForm(request.POST)
        if request.POST.get('id'):
            data=get_object_or_404(Supplier,pk=int(request.POST.get('id')))
            form=SupplierForm(request.POST,instance=data)
        item=[]
        if form.is_valid():
            item = form.save()
            item.save() # save in table 
            if request.POST.get('id'):
                if item.id:
                    result={'status':1,'message':"تم التعديل"}
                else:
                    result={'status':2,'message':"هناك هطاء بالتعديل"}
            else:
                if item.id:
                    result={'status':1,'message':"تم الحفظ"}
                else:
                    result={'status':2,'message':"هناك خطاء الحفظ"}
        else:
            result={'status':0,'error':form.errors.as_json()}
        return JsonResponse(result)
          
    def delete(self, request,*args, **kwargs):
        pk=int(QueryDict(request.body).get('id'))
        if pk:
            try:
                data=get_object_or_404(Supplier,pk=pk)
                data.delete()
                msg="تم الحذف"
                result={'status':1,'message':msg}
            except:
                msg="خطاء بالحذف"
                result={'status':0,'message':msg}
        else:
            msg="لا يوجد الصنف"
            result={'status':0,'message':msg}
        return JsonResponse(result)


class SupplierJson(BaseDatatableView):
    # The model we're going to show
    model = Supplier

    # define the columns that will be returned
    columns = [
        'id',
        "name_lo",
        "name_fk",
        "phone",
        "is_stop",
        "created",
        "action",
  
    ]

    # define column names that will be used in sorting
    # order is important and should be same as order of columns
    # displayed by datatables. For non-sortable columns use empty
    # value like ''
    order_columns = [
          'id',
        "name_lo",
        "name_fk",
        "phone",
        "is_stop",
        "created",
        "action",
  
    ]

    # set max limit of records returned, this is used to protect our site if someone tries to attack our site
    # and make it return huge amount of data
    max_display_length = 500
    count = 0
    def render_column(self, row, column):
      
        if column == "id":
            self.count += 1
            return self.count
        if column == "action":
            return '<a class="edit_row" data-url="{3}" data-id="{0}" style="DISPLAY: -webkit-inline-box;"  data-toggle="tooltip" title="{1}"><i class="fa fa-edit"></i></a><a class="delete_row" data-url="{3}" data-id="{0}"  style="    DISPLAY: -webkit-inline-box;"     data-toggle="tooltip" title="{2}"><i class="fa fa-trash"></i></a>'.format(row.pk,"Edit","Delete",reverse("supplier"))
            
            
        else:
            # We want to render Items as a custom column
            return super(SupplierJson, self).render_column(row, column)

    def filter_queryset(self, qs):
        # use parameters passed in GET request to filter queryset

        # simple example:
        search = self.request.GET.get('search[value]', None)
        if search:
            qs = qs.filter(name__istartswith=search)

        # more advanced example using extra parameters
        filter_customer = self.request.GET.get('customer', None)

        if filter_customer:
            customer_parts = filter_customer.split(' ')
            qs_params = None
            for part in customer_parts:
                q = Q(customer_firstname__istartswith=part) | Q(customer_lastname__istartswith=part)
                qs_params = qs_params | q if qs_params else q
            qs = qs.filter(qs_params)
        return qs

restaurant_managment-main/purchases/views.py
import traceback
from django.shortcuts import render
from django.urls import reverse
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.utils.html import escape
from django.views.generic.edit import CreateView
from django.http import  JsonResponse, HttpResponse
from django.contrib.auth import authenticate
from django.contrib.auth import views as auth_views #new
from django.views import View
from django.core import serializers
from django.shortcuts import get_object_or_404
from django.http import QueryDict
from purchases.models import Purchases,PurchasesDetails
from purchases.forms import PurchasesForm,PurchasesDetailsForm
from django.forms import formset_factory,modelformset_factory
from django.db.models import Max
from django.db import transaction, IntegrityError
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

class PurchaseInvoicelocals(CreateView):
 
    
    def get(self, request, *args, **kwargs):
        """Function For get  Record and render record
        """

        result = {"status": 0, "message": ""}
        if "id" in request.GET.keys():

            if request.GET.get("id"):
                formdata = Purchases.objects.filter(
                    pk=int(request.GET.get("id"))
                )
         

                formsetdata = PurchasesDetails.objects.filter(
                    purchases_id=int(request.GET.get("id"))
                )

               

                result = {
                    "status": 1,
                    "data1": serializers.serialize("json", formdata),
                    "data2": serializers.serialize("json", formsetdata),
                }

             
                return JsonResponse(result)

        else:
            try:
             
                DataFormset = modelformset_factory(
                    PurchasesDetails, form=PurchasesDetailsForm
                )
                formset = DataFormset(
                    request.GET or None,
                    queryset=PurchasesDetails.objects.none(),
                    prefix="PurchasesDetails",
                )
                form1 = PurchasesForm()

                context = {
                    "form": form1,
                    "formset": formset,
                    "url": reverse("purchases"),
                    "title_list": "شاشة المشتريات المحلية",
                    }
            except ObjectDoesNotExist as e:

                data = "خطاء في جلب البيانات يجب عليك مراجعة المطور"
                context = {
                    "error": data,
                }
            return render(request, "purchases/purchases/purchases.html", context)

    def post(self, request, *args, **kwargs):
        result = {"status": 0, 
        "class": "",
        "message": ""}
        form = PurchasesForm(request.POST)
        DataFormset = modelformset_factory(
            PurchasesDetails, form=PurchasesDetailsForm
        )
        formset = DataFormset(
            request.POST or None,
            queryset=PurchasesDetails.objects.none(),
            prefix="PurchasesDetails",
        )

        if form.is_valid() and formset.is_valid():


            try:
               
                obj = form.save(commit=False)
                obj.save()
                if formset.is_valid():
                    details_obj = formset.save(commit=False)

                    for instance in details_obj:

                        instance.purchases_id = obj.id
                        instance.save()
                
                
                if request.POST.get("id_invoice"):
                    msg = "تم التعديل بنجاح"
                    result = {"status": 1, "message": msg}
                else:
                    msg = "تم الحفظ بنجاح"
                    result = {"status": 1, "message": msg}
            except IntegrityError as e:

                traceback.print_exc()

                result["status"] = 3
                result["message"] = {
                    "message": str(e),
                    "class": "alert alert-danger",
                }
                return JsonResponse(result)
            except ObjectDoesNotExist as e:
                traceback.print_exc()

                result = {"status": 3, "message": msg, "msg": "error"}

            except Exception as e:
                traceback.print_exc()
                msg = "inexcpacted error"
                result = {"status": 3, "message": msg, "msg": "error"}

        return JsonResponse(result)

    def delete(self, request, *args, **kwargs):
        result = {"status": 0, "message": ""}
        pk = int(QueryDict(request.body).get("id"))
        if pk:
            try:
                data = get_object_or_404(PurchaseInvoicelocal, pk=pk)

                data.delete()
                msg = message.delete_successfully()
                result = {"status": 1, "message": msg}
            except InvoiceExcept as e:
                result["status"] = 3
                result["message"] = {
                    "message": str(e),
                    "class": "alert alert-danger",
                }
                return JsonResponse(result)
            except Exception as e:
                msg = str(e)
                result = {"status": 3, "message": msg, "msg": "error"}
        else:
            msg = message.delete_error()
            result = {"status": 0, "message": msg}
        return JsonResponse(result)

def max_number(request):
    max_num=[]
    nax_num=Purchases.objects.aggregate(Max('number'))["number__max"]
    if nax_num:
        nax_num=int(nax_num)+1
    else:
        nax_num=1
    

    result={'status':1,"max_number":nax_num}
    return JsonResponse(result)

restaurant_managment-main/purchases/templates/purchases/purchases/purchases.html
{%  extends "base.html" %}

{% load static %} 
{% block title %}
{{title_list}}
{% endblock title %}

{% block content %}
    <form method="post" id='myform_' action="{{ url }}" class="needs-validation" accept-charset="utf-8">
        {% csrf_token %}
        <input type="text" id="id_invoice1" name="id_invoice" class="hidden">
        
     <div class="row">
      <div class="col-md-4 mt-4">
        {{form.number.label}}
        {{form.number}}

          
      </div>
      <div class="col-md-4 mt-4">
        
        {{form.store.label}}
      {{form.store}}
    </div>
    <div class="col-md-4 mt-4">
        {{form.date.label}}
      {{form.date}}
    </div>
    </div>
    <div class="row">
      <div class="col-md-4 mt-4">

          {{form.supplir.label}}
        {{form.supplir}}
      </div>
      <div class="col-md-4 mt-4">
        {{form.notes.label}}
        {{form.notes}}
      </div>
      <div class="col-md-4 mt-4">
    
      </div>
    </div>

    {% load i18n static %} 
    {% csrf_token %}
    
    
    
    <div class="table-responsive mailbox-messages">
        <table class="table table-responsive  table-bordered table-hover" id="show_opration_id">
            <thead class="text-center">
                <tr>
                    <th>{% trans "#" %}</th>
                    <th style="width: 200px;">{% trans "الاصناف" %}</th>
                    <th>{% trans "السعر" %}</th>
                    <th style="width: 200px;">{% trans "الكمية" %}</th>
                    <th style="width: 200px;">{% trans "الإجمالي" %}</th>
                    <th style="width: 100px;">{% trans "تاريخ الإنتهاء" %}</th>
                    
                    <th>{% trans "Action" %}</th>
                </tr>
    
            </thead>
            <tbody class="tbody_tb text-center">
                {{ formset.management_form }}
                {% for f_set in formset %}
                <tr class="item">
                    <td class="td_id">{{ forloop.counter }}</td>
                    <td class="td_two">{{ f_set.items }}</td>
                    <td class="td_first">{{ f_set.price }}</td>
                    <td>{{ f_set.qty }}</td>
                    <td class="td_total">{{ f_set.total }}</td>
                    <td>{{ f_set.date_end }}</td>
                              <td>
                        <button 
                            type="button" 
                            data-toggle="tooltip" 
                            title="Delete" 
                            class="btn btn-dark btn-sm delete_form" 
                            id="{{ f_set.prefix }}">
                            
                                <i 
                                    class="fa fa-trash fa-lg" 
                                    aria-hidden="true"
                                    data-original-title="" 
                                    title="">
                                </i>
                        </button>
                    </td>
                    <td class="hidden">{{f_set.id}}</td>
                </tr>
                {% endfor %}
    
            </tbody>
            <tfoot>
                <tr>
                    <td>
                        <button type="button" data-toggle="tooltip" title="Add Row" class="btn btn-sm btn-green add_form" id="{{ formset.prefix }}">
                                    <i class="fa fa-plus" aria-hidden="true"></i>
                        </button>
                    </td>
                    
                    <td colspan="2" style="border-left: none!important; border-right: none !important; border-bottom: none!important;">
                        {{form.amount.label}}
                        {{form.amount}}
                    </td>
    
    
                </tr>
    
            </tfoot>
    
        </table>
    </div>

    <button type="submit">حفظ</button>
    </form>
{% endblock content %}

{% block scripts %}
<script>
  max_number =()=>{
    $.ajax({
        method: "post",
        url:"{%url 'max_number'%}",
        beforeSend: function (xhr) {
            xhr.setRequestHeader("X-CSRFToken", csrf);
          },
        success: function(data) {
          $("#id_number").val(data.max_number);
        }
      });
  };
</script>
<script>
  let csrf = '{{ csrf_token }}';

  max_number();
  

    
$(document).on('submit', '#myform_', function(e) {
        
        let form_id = '#myform_';
        e.preventDefault();
        $.ajax({
            url: $(this).attr('action'),
            data: $(this).serialize(),
            method: 'POST',
            success: function(data) {
                if (data.status == 1) {
                    alert(data.message);

                    table.ajax.reload();
                } else if (data.status == 2) {
                    $.each(data.error, function() {
                        let form = $(this)[0].form_id;
                        alert($(this)[0].message);
                    });
                } else if (data.status == 0) {
                    alert(data.message);
                    

                    let invoice_rows = parseInt($('#id_' + 'PurchasesDetails' + '-TOTAL_FORMS').val());

                    if (!data.error == "") {
                        alert(data.error);
                        let row_id = data.error.form_id;
                        let row_id2 = data.error['myform_'];
                        let error = JSON.parse(data.error.error);
                        $.each(error, function(i, value) {
                            let div = '<span class="text-danger">';
                            $.each(value, function(j, message) {
                                div += `- ${message.message}<br>`;
                            });

                            $(`#id_${row_id}-0-${i}`).parent().append(div);
                        });
                    }
                    if (!data.error2 == "") {



                        let error2 = JSON.parse(data.error2);

                    
                        $.each(error2, function(i, value) {
                            
                            let div = '<span class="text-danger">';
                            $.each(value, function(j, message) {
                                div += `- ${message.message}<br>`;
                                alert(String(message.message));
                            });
                            $(`#PurchasesDetails-${data.row}-${i}`).parent().append(div);
                        });
                    }
                
            } else if (data.status == 3) {
                alert(data.message)
            }
                $('#submit-button').button('reset');
            },
            error: function(data) {
                

                alert('خطاء');
            }
        });
    
    });




$(document).on('click','.edit_row',function(){
 
    $.ajax({
          url: $(this).data('url'),
          data: {'id':$(this).data('id')},
          type: 'GET',
          success: function (data) {
              let resp=JSON.parse(data.data);
              if(data.status==1){
                  
              $(`input[name="id"]`).val(resp[0].pk);
              $.each(resp[0].fields,function(i,value){
                  $(`input[name="${i}"]`).val(value);
                  $(`select[name="${i}"] option[value="${value}"]`).attr('selected','selected');
              });
            $('#modal-lg').modal('show');

          }
         else{
          console.log(data.error);
         }
     },
     error:function(data){
     }
 });
});

$(document).on('click','.delete_row',function(){

 if(confirm('هل حقا تريد الحذف؟')){
    let id_row=$(this).data('id');
    $.ajax({
        url: $(this).data('url'),
        data: {
         'id':id_row,
     },
     method: 'DELETE',
     beforeSend: function (xhr) {
             xhr.setRequestHeader("X-CSRFToken",csrf);
         },
     success: function (data) {
        
         if(data.status==1){
          alert(data.message)   
       
          $('.datatable').DataTable().ajax.reload();
          
        }
        if(data.status==0)
          alert(data.message)   

      
     },
     error:function(data){
     }
 });
}
});

$(document).ready(function () {
    var oTable = $('.datatable').dataTable({
        // ...
        "processing": true,
        "serverSide": true,
        "ajax": "{% url 'SupplierJson' %}"
    });
    // ...
});



$(document).on('click', '.add_form', function() {
    let prefix = String($(this).attr('id'));
    var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
    var row = $(".item:last").clone(false).get(0);
    
    $(row).find('.td_two').attr('data-select2-id', formCount);
    $(row).find('.td_id').text(formCount + 1);
    $(row).find('.formset-field').each(function() {
        updateElementFormset(this, prefix, formCount);
        $(this).val('');
        $(this).removeAttr('value');
        $(this).removeAttr('disabled');
        $(this).removeAttr('readonly');
    });
    $(row).find('.td_total').children('input').attr('readonly', 'readonly');
    $('.tbody_tb').append(row);
    
    $(row).find(".delete_form").click(function() {
        return deleteFormset(this, prefix);
    });
    $('#id_' + prefix + '-TOTAL_FORMS').val(formCount + 1);

});

$(document).on('click', '.delete_form', function() {
    deleteFormset($(this), String($(this).attr('id')));
});

function deleteFormset(btn, prefix) {
    var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
    if (formCount > 1) {
        $(btn).parents('.item').remove();
        var forms = $('.item'); 
        $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
        var i = 0;
        for (formCount = forms.length; i < formCount; i++) {
            $(forms.get(i)).find('.formset-field').each(function() {
                $(forms.get(i)).find('.td_id').text(i + 1);
                updateElementFormset(this, prefix, i);
            });
        }
        get_total();
    } 
    return false;
}


getTotalItem=(element_id)=>{
    let total_items = 0;
    var x = element_id.id.split('-');
    var qty_p=$('#id_PurchasesDetails-' + x[1] + '-qty').val();
    var price_p=$('#id_PurchasesDetails-' + x[1] + '-price').val();
    if(!isNaN(parseInt(qty_p))&& !isNaN(parseInt(price_p))){

        total_items =(parseInt(qty_p)*parseInt(price_p));
    }
    $('#id_PurchasesDetails-' + x[1] + '-total').val(total_items);
    get_total();
}

function get_total() {
    let total_items = 0;
    $('.total_items').each(function() {
        if (!isNaN(parseFloat($(this).val()))) {
            total_items += parseFloat($(this).val());
        }
    });

    $('#id_amount').val(total_items);
    
}


</script>
<script>
    function updateElementFormset(el, prefix, ndx) {
        var id_regex = new RegExp('(' + prefix + '-\\d+-)');
        var replacement = prefix + '-' + ndx + '-';
        if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex,
            replacement));
        if (el.id) el.id = el.id.replace(id_regex, replacement);
        if (el.name) el.name = el.name.replace(id_regex, replacement);
}

</script>

{% endblock scripts %}